language: node_js
node_js:
  - "node"
before_install:
  - npm install -g unitejs-cli@1.5.1
  - npm install -g gulp
  - unite configure --profile=PreactTypeScript --title="Docker QuickStart" --packageName=unitejs-docker-quickstart --outputDirectory=./
  - unite platform --operation=add --platformName=Docker
  - cd www
install:
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp e2e-install || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp build --buildConfiguration=prod || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp platform-docker-package --buildConfiguration=prod
cache:
  directories:
  - www/node_modules
