language: node_js
sudo: required
services:
  - docker
node_js:
  - "8"
before_install:
  - npm install -g unitejs-cli
  - npm install -g gulp
  - unite configure --profile=PreactTypeScript --title="Docker QuickStart" --packageName=unitejs-docker-quickstart --outputDirectory=./
  - unite platform --operation=add --platformName=Docker
  - cd www
install:
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp e2e-install --drivers=chrome@2.33 || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp build --buildConfiguration=prod || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp platform-docker-package --buildConfiguration=prod || travis_terminate 1

